name: RT-Thread_Packages

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  # Runs at 00:00 UTC on the 1, 16 and 31th of every month
  schedule:
    - cron:  '0 0 */15 * *'
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  pkgs-test:
    uses: RT-Thread/pkgs-test/.github/workflows/pkgs-action.yml@main
